### ISSUE TITLE
Could not load item for book default on page 2 at position 35

### ISSUE THREAD

**Issue by FluffyDiscord** [hamstar0/tml-extensibleinventory-mod#26]
Characters are constantly being corrupted. Occurs randomly. Can not really go back, as I would lose many pages.

Full log: https://pastebin.com/m88e3kDP

Expectations: removes and notices use about buggy item, maybe reports which mod it belongs to

**Comment by hamstar0** [comment]
Did you disable any mods recently by chance?

**Comment by FluffyDiscord** [comment]
The only one I disabled while playing with this character was a Chads Furniture, but I did not have any item from this mod in my inventory or in world.
However it did not start doing after disabling it, just happens randomly. (loaded backup day old and after saving few times, it did again)

**Comment by hamstar0** [comment]
If you send me your affected player's files (.plr and .tplr), I can try to figure out what's going on from the file data.

**Comment by FluffyDiscord** [comment]
Sending the files, hopefully you can get something from them

[Players.zip](https://github.com/hamstar0/tml-extensibleinventory-mod/files/3179233/Players.zip)
